import { renderTargetSize, sanitizeDpr } from "./coords";
import type { Region, SurfaceImage } from "./types";

/**
 * Overlay canvas (#20).
 *
 * The overlay is a single absolutely-positioned `<canvas>` inserted as the
 * FIRST child of the host element:
 *
 * - `position: absolute` at the document origin, sized to the scene region,
 *   so it moves with the page on scroll (document-relative scene space) and
 *   clips cast shadows at the region boundary
 * - `pointer-events: none` — hit-testing, focus, keyboard and pointer events
 *   belong entirely to the DOM underneath; the canvas never captures them
 * - `z-index: 0` and inserted BEFORE the page content: it paints above the
 *   host background (so cast shadows on the "base plane" are visible) but
 *   below any later positioned content, including the registered surfaces
 *   (which the layer forces `position: relative`, so their DOM text stays
 *   above the physical layer)
 * - `aria-hidden="true"`, `role="presentation"` and `tabindex="-1"`: the
 *   canvas is inert to the accessibility tree and to focus
 *
 * The backing store is DPR-scaled (`floor(region.w * dpr)` texels) while the
 * CSS size stays in CSS pixels, so `putImageData` writes crisp device pixels.
 */

export interface Overlay {
  /** Resize + reposition the canvas to cover `region` at `dpr`. */
  resizeAndPosition(region: Region, dpr: number): void;
  /** Draw a full-scene image (1 texel = 1 canvas device pixel). */
  paint(image: SurfaceImage): void;
  /** Make the canvas fully transparent (nothing to render). */
  clear(): void;
  dispose(): void;
}

export const OVERLAY_STYLE_PROPS = {
  position: "absolute",
  zIndex: "0",
  pointerEvents: "none",
} as const;

export class OverlayCanvas implements Overlay {
  readonly canvas: HTMLCanvasElement;

  constructor(host: Element, zIndex = 0) {
    const canvas = document.createElement("canvas");
    canvas.style.position = OVERLAY_STYLE_PROPS.position;
    canvas.style.zIndex = String(zIndex);
    canvas.style.pointerEvents = OVERLAY_STYLE_PROPS.pointerEvents;
    canvas.style.left = "0px";
    canvas.style.top = "0px";
    canvas.style.width = "0px";
    canvas.style.height = "0px";
    canvas.setAttribute("aria-hidden", "true");
    canvas.setAttribute("role", "presentation");
    canvas.tabIndex = -1;
    this.canvas = canvas;
    host.insertBefore(canvas, host.firstChild);
  }

  resizeAndPosition(region: Region, dpr: number): void {
    const { width, height } = renderTargetSize(region, sanitizeDpr(dpr));
    this.canvas.width = width;
    this.canvas.height = height;
    this.canvas.style.left = `${region.x}px`;
    this.canvas.style.top = `${region.y}px`;
    this.canvas.style.width = `${region.w}px`;
    this.canvas.style.height = `${region.h}px`;
  }

  paint(image: SurfaceImage): void {
    const ctx = this.canvas.getContext("2d");
    if (ctx === null) {
      return;
    }
    const img = new ImageData(image.data, image.width, image.height);
    ctx.putImageData(img, 0, 0);
  }

  clear(): void {
    const ctx = this.canvas.getContext("2d");
    if (ctx === null) {
      return;
    }
    ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
  }

  dispose(): void {
    this.canvas.remove();
  }
}

export interface SavedStyle {
  prop: string;
  value: string;
  priority: string;
}

/**
 * Inline-style properties the layer overrides on a registered surface so the
 * physical appearance is not double-rendered by the original DOM:
 *
 * - `background`: the renderer paints the surface relief on the overlay, so
 *   the element's own background must become transparent
 * - `box-shadow`: cast shadows / relief shading are generated by the renderer;
 *   the element's CSS shadow would paint a second, unlit copy
 *
 * Text color, borders, outlines (including the `:focus-visible` ring),
 * `cursor` and all other content/affordance styles stay DOM-owned.
 */
export const SUPPRESSED_PROPS: ReadonlyArray<readonly [string, string]> = [
  ["background", "transparent"],
  ["box-shadow", "none"],
];

/** Force the registered surface to paint above the overlay (required for its
 * DOM text to remain visible over the physical layer). */
export const SURFACE_POSITION = "relative";

/**
 * Save + suppress the element's background/shadow inline styles so the
 * physical layer is the single source of appearance. Returns the saved styles
 * for `restoreSavedStyles`.
 */
export function applySuppression(element: HTMLElement): SavedStyle[] {
  const saved: SavedStyle[] = [];
  for (const [prop, value] of SUPPRESSED_PROPS) {
    saved.push({
      prop,
      value: element.style.getPropertyValue(prop),
      priority: element.style.getPropertyPriority(prop),
    });
    element.style.setProperty(prop, value, "important");
  }
  const currentPosition = element.style.getPropertyValue("position");
  const computedPosition =
    typeof getComputedStyle === "function" ? getComputedStyle(element).position : "static";
  if (computedPosition === "static") {
    saved.push({
      prop: "position",
      value: currentPosition,
      priority: element.style.getPropertyPriority("position"),
    });
    element.style.setProperty("position", SURFACE_POSITION);
  }
  return saved;
}

/** Restore inline styles saved by `applySuppression` (mount -> unmount). */
export function restoreSavedStyles(element: HTMLElement, saved: SavedStyle[]): void {
  for (const { prop, value, priority } of saved) {
    if (value === "" && priority === "") {
      element.style.removeProperty(prop);
    } else {
      element.style.setProperty(prop, value, priority);
    }
  }
}
