import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
// @ts-expect-error - scripts/build-wasm.mjs is a plain ESM CLI without declarations
import { buildNormalKernelModule } from "../../scripts/build-wasm.mjs";
import { NORMAL_KERNEL_BASE64, NORMAL_KERNEL_BYTE_LENGTH } from "./normal-kernel.base64";

/**
 * #33 deterministic WASM build gate.
 *
 * The checked-in base64 module (normal-kernel.base64.ts) is regenerated by
 * `node scripts/build-wasm.mjs --emit`. This test pins the two to each
 * other:
 *
 *   - a fresh deterministic build must produce byte-identical output on
 *     every invocation (run twice in-process),
 *   - the checked-in base64 must decode to exactly those bytes (no silent
 *     drift between the build script and the shipped module),
 *   - the shipped module must instantiate and compute (smoke).
 *
 * There is no external toolchain dependency: the build script emits the
 * binary directly from the structured spec (see its opcode-table comment;
 * every opcode used by the kernel was verified empirically against the
 * engine before being committed to the table).
 */

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const watPath = resolve(packageRoot, "src", "wasm", "normal-kernel.wat");

describe("#33 WASM module determinism", () => {
  it("builds the same bytes on every invocation", () => {
    const a = buildNormalKernelModule();
    const b = buildNormalKernelModule();
    expect(a).toEqual(b);
  });

  it("checked-in base64 decodes to exactly the deterministic build", () => {
    const built = buildNormalKernelModule();
    expect(NORMAL_KERNEL_BYTE_LENGTH).toBe(built.length);
    const checked = Uint8Array.from(atob(NORMAL_KERNEL_BASE64), (c) => c.charCodeAt(0));
    expect(checked).toEqual(built);
  });

  it("the audit WAT documents the kernel (module + both exports)", () => {
    // The WAT file is documentation for human audit; pin the invariants it
    // must always state so it cannot silently drift out of sync with the
    // kernel's actual contract.
    const wat = readFileSync(watPath, "utf8");
    expect(wat).toContain('(func (export "kernel_version") (result i32)');
    expect(wat).toContain('(func (export "compute_normals")');
    expect(wat).toContain("(memory (export \"memory\") 1 65536)");
    expect(wat).toContain("scripts/build-wasm.mjs");
  });

  it("the built module instantiates and computes a normal (smoke)", async () => {
    const built = buildNormalKernelModule();
    const { instance } = await WebAssembly.instantiate(built, {});
    const memory = instance.exports.memory as WebAssembly.Memory;
    const width = 4;
    const height = 4;
    const input = new Float32Array(memory.buffer, 0, width * height);
    input[5] = 1; // a single raised texel
    const ret = (instance.exports.compute_normals as (...a: number[]) => number)(
      width,
      height,
      0.5,
      0.5,
      1,
    );
    expect(ret).toBe(0);
    const out = new Float32Array(memory.buffer, 4 * width * height, width * height * 3);
    // the raised texel's own normal is exactly +z (flat plateau around it);
    // -0 components are legal (the oracle produces -0 there too — exact
    // bit-parity is asserted in kernel.test.ts)
    expect(Math.abs(out[15])).toBe(0);
    expect(Math.abs(out[16])).toBe(0);
    expect(out[17]).toBe(1);
    // the left neighbor sees the height rise toward +x: dx > 0 -> nx < 0
    expect(out[4 * 3]).toBeLessThan(0);
  });
});
