import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { describe, expect, it } from "vitest";
// The report generator is a plain ESM CLI script without type declarations;
// importing its pure parity parser for contract tests is intentional. The
// script only runs main() under an isMain guard, so importing it is safe.
// @ts-expect-error - scripts/bench-issue-48-report.mjs has no type declarations
import { parseParityResult } from "../../scripts/bench-issue-48-report.mjs";
// @ts-expect-error - test-browser modules are plain ESM without declarations
import { ISSUE_48_ADVERSARIAL_FIXTURE_IDS } from "../../test-browser/catalog.mjs";

/**
 * #48 report generator contract:
 *
 * - ISSUE_48_PERFORMANCE_REPORT.md is machine-generated by
 *   scripts/bench-issue-48-report.mjs; the report must carry the profiling /
 *   candidate-evaluation / adopted-algorithm / correctness-evidence sections
 *   required by the issue's acceptance criteria.
 * - The fixture ID list in the correctness evidence is rendered from the
 *   #48 adversarial fixture set declared once in test-browser/catalog.mjs.
 * - The checked-run PASS numbers are parsed from the committed real-WebGPU
 *   parity artifact; the generator refuses to emit the report unless the run
 *   is a real-adapter PASS with zero missing IDs / execution errors /
 *   mismatches, and it never hardcodes a PASS string.
 */
const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const repoRoot = resolve(packageRoot, "..", "..");

const generatorSource = readFileSync(resolve(packageRoot, "scripts", "bench-issue-48-report.mjs"), "utf8");
const reportSource = readFileSync(resolve(repoRoot, "ISSUE_48_PERFORMANCE_REPORT.md"), "utf8");
const parityResult = parseParityResult(
  readFileSync(resolve(packageRoot, "parity-results-issue-48.txt"), "utf8"),
);

const SECTION_HEADINGS = [
  "## Profiling / bottleneck analysis",
  "## Candidate evaluation",
  "## Adopted algorithm",
  "## Correctness evidence",
];

describe("bench-issue-48-report.mjs — generator emits the required analysis sections", () => {
  it("contains every required section heading", () => {
    for (const heading of SECTION_HEADINGS) {
      expect(generatorSource).toContain(heading);
    }
  });

  it("renders the fixture list mechanically from the #48 adversarial catalog set", () => {
    expect(generatorSource).toContain("ISSUE_48_ADVERSARIAL_FIXTURE_IDS");
    expect(generatorSource).toContain(
      "...ISSUE_48_ADVERSARIAL_FIXTURE_IDS.map((id) => `- \\`${id}\\``),",
    );
  });

  it("never hardcodes a clean-gate claim; the numbers are parsed from the parity artifact", () => {
    expect(generatorSource).toContain('parity.marker !== "UKIBORI_WEBGPU_PASS"');
    expect(generatorSource).not.toContain("missing 0, execution errors 0");
    expect(generatorSource).not.toContain("mismatches 0.");
  });
});

describe("parseParityResult — honest parity evidence parsing", () => {
  const summaryPayload =
    '{"adapter":{"vendor":"nvidia","architecture":"blackwell"},"fixtures":1,' +
    '"issue48Adversarial":{"expected":["a"],"executed":["a"],"missing":[],"executionErrors":[],"mismatches":[]}}';

  it("parses the anchored marker and SUMMARY payload", () => {
    const parsed = parseParityResult(`UKIBORI_WEBGPU_PASS all good\nSUMMARY ${summaryPayload}\n`);
    expect(parsed.marker).toBe("UKIBORI_WEBGPU_PASS");
    expect(parsed.summary.issue48Adversarial.expected).toEqual(["a"]);
  });

  it("rejects a first line without an anchored marker token", () => {
    expect(() => parseParityResult("no marker here\nSUMMARY {}")).toThrow();
    expect(() => parseParityResult("UKIBORI_WEBGPU_PASS-evil suffix\nSUMMARY {}")).toThrow();
    expect(() => parseParityResult("\nSUMMARY {}")).toThrow();
  });

  it("rejects a missing or non-JSON SUMMARY line", () => {
    expect(() => parseParityResult("UKIBORI_WEBGPU_PASS only")).toThrow();
    expect(() => parseParityResult("UKIBORI_WEBGPU_PASS x\nSUMMARY not-json")).toThrow();
  });
});

describe("ISSUE_48_PERFORMANCE_REPORT.md — generated report contract", () => {
  it("contains every required section heading", () => {
    for (const heading of SECTION_HEADINGS) {
      expect(reportSource).toContain(heading);
    }
  });

  it("pins every #48 adversarial fixture ID in the correctness evidence", () => {
    expect(ISSUE_48_ADVERSARIAL_FIXTURE_IDS.length).toBe(17);
    for (const id of ISSUE_48_ADVERSARIAL_FIXTURE_IDS) {
      expect(reportSource).toContain(`- \`${id}\``);
    }
  });

  it("records candidate verdicts for the evaluated candidates", () => {
    for (const heading of [
      "### Hierarchical / mip-based height bounds",
      "### Tile / cluster spatial blocker bounds",
      "### Adaptive stepping",
      "### Height-field layout / shared-memory / coalescing redesign",
      "### Exact prefix binary search + caster AABB empty-space culling",
    ]) {
      expect(reportSource).toContain(heading);
    }
    expect(reportSource).toContain("**Rejected / deferred.**");
    expect(reportSource).toContain("**Rejected.**");
    expect(reportSource).toContain("**Deferred.**");
    expect(reportSource).toContain("**Adopted.**");
  });

  it("pins the adopted algorithm's semantic-preservation and resource contract", () => {
    for (const text of [
      "Historical sample positions are unchanged",
      "`dz > 0`",
      "`dz <= 0`",
      "No analytic ratio, no epsilon, and no magic step margin",
      "extra passes = 0",
      "extra dispatches = 0",
      "extra uploads = 0",
      "extra storage bytes = 0",
      "negative threshold",
    ]) {
      expect(reportSource).toContain(text);
    }
  });

  it("records the committed real-WebGPU checked run with a clean #48 gate", () => {
    const adversarial = parityResult.summary.issue48Adversarial;
    expect(parityResult.marker).toBe("UKIBORI_WEBGPU_PASS");
    expect(adversarial.expected).toEqual([...ISSUE_48_ADVERSARIAL_FIXTURE_IDS]);
    expect(adversarial.missing).toEqual([]);
    expect(adversarial.executionErrors).toEqual([]);
    expect(adversarial.mismatches).toEqual([]);
    expect(reportSource).toContain("marker `UKIBORI_WEBGPU_PASS` on a real adapter");
  });

  it("records the deterministic historical-vs-optimized prefix sweep", () => {
    expect(reportSource).toContain("12,000-case");
    expect(reportSource).toContain("shadow-prefix.test.ts");
  });

  it("keeps the report explicitly unmerged/unclosed", () => {
    expect(reportSource).toContain("Issue #48 は閉じていません");
  });
});
